// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

export default function printModuleAProp() {
  console.log(testProp);
}
